GET
http://localhost:8080/animes
%%%

# Duration: 33079 ms
# URL: http://localhost:8080/animes

# HTTP/1.1 500 Internal Server Error

@Content-Type: application/json
@Content-Length: 132

{
  "timestamp": "2021-08-23T18:38:01.159+00:00",
  "path": "/animes",
  "status": 500,
  "error": "Internal Server Error",
  "requestId": "cb57c244-1"
}